### ISSUE TITLE
SQS Message handling settings don't work.

### ISSUE THREAD

**Issue by alexgleith** [digitalearthafrica/crop-mask#105]
It should be possible to use Statistician configuration parameters for crop mask like this:

``` yaml
          # SQS Message Handling
          max_processing_time: 0    # Take as long as you want
          job_queue_max_lease: 600  # Lease for 10 minutes at a time
          renew_safety_margin: 30   # Extend with 30 seconds remaining
          future_poll_interval: 10  # Check every 10 seconds
```

But this doesn't work, as evidenced by the weird behaviour in messages below.

What I think is happening is that messages are going back on the queue and being retried, so that they end up being run multiple times in parallel... this should _not_ happen as it's extremely wasteful of resources.

The solution is to use long timeouts, which slows down retries for real failures.

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/3445853/163086778-55483af0-4cb3-4a03-adb3-973d3721df2f.png">
